// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using unip_pim_viii_data_access_object.Models;

namespace unip_pim_viii_data_access_object.Migrations
{
    [DbContext(typeof(PIMContext))]
    [Migration("20211031024737_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cep")
                        .HasColumnType("int");

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("cpf")
                        .HasColumnType("bigint");

                    b.Property<int?>("enderecoid")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("enderecoid");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.Telefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Pessoaid")
                        .HasColumnType("int");

                    b.Property<int>("ddd")
                        .HasColumnType("int");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.Property<int?>("tipoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Pessoaid");

                    b.HasIndex("tipoid");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.TipoTelefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoTelefones");
                });

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.Pessoa", b =>
                {
                    b.HasOne("unip_pim_viii_data_access_object.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoid");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.Telefone", b =>
                {
                    b.HasOne("unip_pim_viii_data_access_object.Models.Pessoa", null)
                        .WithMany("telefones")
                        .HasForeignKey("Pessoaid");

                    b.HasOne("unip_pim_viii_data_access_object.Models.TipoTelefone", "tipo")
                        .WithMany()
                        .HasForeignKey("tipoid");

                    b.Navigation("tipo");
                });

            modelBuilder.Entity("unip_pim_viii_data_access_object.Models.Pessoa", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
